# Generated by Django 5.2.17 on 2026-09-25 17:37

import django.db.models.deletion
from django.db import migrations, models

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks

import tests.testapp.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="GalleryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("images", 0),
                            ("captioned_images", 1),
                            ("image_blocks", 2),
                            ("documents", 3),
                            ("pages", 4),
                            ("authors", 5),
                            ("unique_images", 6),
                            ("three_images", 7),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                                (wagtail.images.blocks.ImageChooserBlock(),),
                                {},
                            ),
                            1: (
                                "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                                (
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("image", wagtail.images.blocks.ImageChooserBlock()),
                                            ("caption", wagtail.blocks.CharBlock(required=False)),
                                        ]
                                    ),
                                ),
                                {"chooser_field_name": "image"},
                            ),
                            2: (
                                "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                                (wagtail.images.blocks.ImageBlock(),),
                                {"chooser_field_name": "image"},
                            ),
                            3: (
                                "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                                (wagtail.documents.blocks.DocumentChooserBlock(),),
                                {},
                            ),
                            4: (
                                "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                                (wagtail.blocks.PageChooserBlock(),),
                                {},
                            ),
                            5: (
                                "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                                (
                                    wagtail.snippets.blocks.SnippetChooserBlock(
                                        tests.testapp.models.Author
                                    ),
                                ),
                                {},
                            ),
                            6: (
                                "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                                (wagtail.images.blocks.ImageChooserBlock(),),
                                {"allow_duplicates": False},
                            ),
                            7: (
                                "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                                (wagtail.images.blocks.ImageChooserBlock(),),
                                {"max_num": 3},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
