# Generated by Django 5.2.17 on 2026-09-25 19:13

from django.db import migrations

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks
import wagtail_multiple_chooser_block.contrib.bulk_upload.blocks

import tests.testapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerypage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("images", 0),
                    ("captioned_images", 1),
                    ("image_blocks", 2),
                    ("documents", 3),
                    ("pages", 4),
                    ("authors", 5),
                    ("unique_images", 6),
                    ("three_images", 7),
                    ("bulk_images", 8),
                    ("bulk_documents", 9),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                        (wagtail.images.blocks.ImageChooserBlock(),),
                        {},
                    ),
                    1: (
                        "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                        (
                            wagtail.blocks.StructBlock(
                                [
                                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                                    ("caption", wagtail.blocks.CharBlock(required=False)),
                                ]
                            ),
                        ),
                        {"chooser_field_name": "image"},
                    ),
                    2: (
                        "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                        (wagtail.images.blocks.ImageBlock(),),
                        {"chooser_field_name": "image"},
                    ),
                    3: (
                        "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                        (wagtail.documents.blocks.DocumentChooserBlock(),),
                        {},
                    ),
                    4: (
                        "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                        (wagtail.blocks.PageChooserBlock(),),
                        {},
                    ),
                    5: (
                        "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                        (wagtail.snippets.blocks.SnippetChooserBlock(tests.testapp.models.Author),),
                        {},
                    ),
                    6: (
                        "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                        (wagtail.images.blocks.ImageChooserBlock(),),
                        {"allow_duplicates": False},
                    ),
                    7: (
                        "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                        (wagtail.images.blocks.ImageChooserBlock(),),
                        {"max_num": 3},
                    ),
                    8: (
                        "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                        (
                            wagtail_multiple_chooser_block.contrib.bulk_upload.blocks.BulkUploadImageBlock(),
                        ),
                        {"chooser_field_name": "image"},
                    ),
                    9: (
                        "wagtail_multiple_chooser_block.blocks.MultipleChooserBlock",
                        (
                            wagtail_multiple_chooser_block.contrib.bulk_upload.blocks.BulkUploadDocumentChooserBlock(),
                        ),
                        {},
                    ),
                },
            ),
        ),
    ]
